# Generated by Django 4.1.5 on 2023-01-29 11:13

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cause',
            field=models.CharField(choices=[('goods', 'GOODS'), ('adoption', 'ADOPTIONS'), ('shelter', 'SHELTER'), ('animal healthcare', 'ANIMAL HEALTHCARE'), ('events', 'EVENTS')], default='ADOPTION', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 11, 13, 39, 363349)),
        ),
        migrations.AddField(
            model_name='project',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 29, 11, 13, 39, 363342)),
        ),
    ]
