# Generated by Django 4.1.5 on 2023-01-29 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_cause_project_date_end_project_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cause',
            field=models.CharField(choices=[('goods', 'GOODS'), ('adoption', 'ADOPTION'), ('shelter', 'SHELTER'), ('animal healthcare', 'ANIMAL HEALTHCARE'), ('events', 'EVENTS')], default='ADOPTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 29, 12, 37, 42, 193982)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 12, 37, 42, 193990)),
        ),
    ]
